export default {
    name: "Omni",
    landingPage: {
        home:"Hogar ",
        about:"Acerca de",
        faqs:"Preguntas Frecuentes",
        hero:"El nacimiento de la Web",
        login:"Inicio de sesión",
        barberBookingApp:"Aplicación de reserva de peluquería.",
        barberBookingAppSub:"¿Por qué usar varias aplicaciones cuando puedes usar solo una? OrderEase tiene todo lo que necesita para administrar la gestión de inventario y el cumplimiento de pedidos con nuestra poderosa plataforma SaaS.",
        getStartedNow:"¡Comience ahora!",
        watchVideo:"Ver video",
        whoAreWe:"Quiénes somos",
        whoAreWeSub:"Bienvenido a nuestro barbero ap",
        testimonials:"Testimonios",
        whatOurUsersThink:"Lo que piensan nuestros usuarios",
        frequentlyAskedQuestions:"Preguntas frecuentes",
        whyDoINeedToCreateAnAccount:"¿Por qué necesito crear una cuenta?",
        whyDoINeedToCreateAnAccountSub:"Si usted es un barbero que busca proporcionar servicios en el hogar, debe registrarse como barbero independiente o si es una tienda que ofrece servicios de peluquería en el hogar o en una tienda, debe crear una cuenta.",
        downloadOmniMobileApp:"Descargar Omni Mobile App",
        downloadOnTheAppStore:"Descargar en la App Store",
        getItOnGooglePlay:"CONSÍGUELO EN Google Play",
        copyright:"Copyright © 2023 - Todos los derechos reservados",
        siteMap:"Mapa del sitio",
        socialLinks:"Enlaces sociales",
        termsConditions:"Términos y condiciones",
        privacyPolicy:"Política de Privacidad",
        aboutUs:"Sobre nosotros",
        
    },

    login: {
        makeNewAccount:"¡Crea una nueva cuenta!",
        signupifyouwanttomakeaccount:"Regístrate si quieres hacer una cuenta",
        signup:"Únete",
        welcomeback:"Bienvenido",
        pleaseLogIn:"Por favor, inicie sesión en su cuenta",
        forgotPassword:"¿Olvidaste tu contraseña?",
        login:"Inicia sesión",
        
    },
    forgotPassword: {
        forgotPassword:"Olvidé mi contraseña",
        forgotPasswordSub:"Por favor, introduzca su dirección de correo electrónico asociada con su cuenta.",
        email:"Correo electrónico",
        send:"Enviar",
        returnToLogin:"Volver a iniciar sesión",
        
    },
    register: {
        signup:"Suscríbete",
        fullname:"Nombre completo",
        email:"Correo electrónico",
        password:"Contraseña",
        alreadyHaveAnAcount:"¡Ya tienes un acocunt!",
        logintoyouraccount:"Inicie sesión en su cuenta",
        createAccount:"Crear cuenta de vendedor",
        login:"Inicia sesión",
        fullNameRequired:"Nombre completo es un campo obligatorio",
        emailRequired:"El correo electrónico es un campo obligatorio",
        passwordRequired:"La contraseña es un campo obligatorio",
        
    },
    selectService: {
        selectService:"Seleccione lo que le describe",
        freelanceBarber:"Barbero Freelance",
        freelanceBarberSub:"Elija esta opción si usted es un barbero independiente que ofrece servicios de peluquería en el hogar.",
        barberShop:"Peluquería",
        barberShopSub:"Elija esta opción si posee una peluquería con varios barberos y está interesado en vender productos cosméticos",
        next:"Siguiente",
        
    },
    freelanceBarber: {
        save:"Guardar",
basicInfo:"Información básica",
services:"Servicios",
WorkingDaysHours:"Días/horas laborables",
location:"Ubicación",
providethefollowing:"Proporcione la siguiente información",
fullName:"Nombre completo",
email:"Correo electrónico",
password:"Contraseña",
about:"Acerca de",
licence:"¿Tiene una licencia o certificación?",
title:"Título",
saveandNext:"Guardar y Siguiente",
whatServicesProvide:"¿Qué servicios están brindando?",
shopwhatServicesProvide:"¿Qué servicios ofrece su barbero?",
addServices:"Agregar servicios",
goBack:"Volver",
next:"Siguiente",
edit:"Editar",
remove:"Eliminar",
setWorkDaysHours:"Establecer días y horas de trabajo",
shopsetWorkDaysHours:"Establezca el horario de su barbero",
mon:"Mon",
tue:"Martes",
wed:"Miércoles",
thu:"Jue",
fri:"Vie",
sat:"Sábado",
sun:"Sol",
monday:"Lunes",
tuesday:"Martes",
wednesday:"Miércoles",
thursday:"Jueves",
friday:"Viernes",
saturday:"Sábado",
sunday:"Domingo",
chooseStartTime:"Elija la hora de inicio",
to:"Para",
chooseEndTime:"Elija la hora de finalización",
selectTime:"SELECCIONAR HORA",
ok:"OK",
cancel:"CANCELAR",
setAsNonWorking:"Establecer como no funciona",
setForAll:"Configurado para todos",
enterLocation:"Ingrese a una ubicación donde pasa la mayor parte de su tiempo",
confirmandSignup:"Confirme y regístrese",
markitonmap:"Márcalo en el mapa",
nonWorkingDay:"Día no laborable",

    },
    addBarberBarber: {
        basicInfo:"Información básica",
        services:"Servicios",
        location:"Ubicación",
        createShop:"Crear tienda",
        shopLogo:"Logotipo de la tienda",
        addCover:"Agregar foto de portada de tiendas",
        shopName:"Nombre de la tienda",
        email:"Correo electrónico",
        password:"Contraseña",
        about:"Acerca de",
        licence:"¿Tiene una licencia o certificación?",
        title:"Título",
        saveandNext:"Guardar y Siguiente",
        whatServicesProvide:"¿Qué servicios están brindando?",
        addServices:"Agregar servicios",
        goBack:"Volver",
        next:"Siguiente",
        edit:"Editar",
        remove:"Eliminar",
        setWorkDaysHours:"Establecer días y horas de trabajo",
        yourSchedule:"Tu horario",
        mon:"Mon",
        tue:"Martes",
        wed:"Miércoles",
        thu:"Jue",
        fri:"Vie",
        sat:"Sábado",
        sun:"Sol",
        monday:"Lunes",
        tuesday:"Martes",
        wednesday:"Miércoles",
        thursday:"Jueves",
        friday:"Viernes",
        saturday:"Sábado",
        sunday:"Domingo",
        chooseStartTime:"Elija la hora de inicio",
        to:"Para",
        chooseEndTime:"Elija la hora de finalización",
        selectTime:"SELECCIONAR HORA",
        ok:"OK",
        cancel:"CANCELAR",
        setAsNonWorking:"Establecer como no funciona",
        setForAll:"Configurado para todos",
        enterLocation:"Ingrese a una ubicación donde pasa la mayor parte de su tiempo",
        confirmandSignup:"Confirme y regístrese",
        markitonmap:"Márcalo en el mapa",
        
    },
    barberInShop: {
        barberShopCreated:"Barbería creada",
        successfuly:"¡Exitosamente!",
        next:"Siguiente",
        addBarbertoYourShop:"Añade barberos a tu tienda",
        addBarber:"Añadir barberos",
        skip:"Saltarse",
        titleShop:"Crear tienda",
        titleShopLocation:"¿Dónde se encuentra su tienda?",
        
    },
    dashboard: {
        termsOfUse:"Términos de uso",
        privacyPolicy:"Política de Privacidad",
        logout:"Cerrar sesión",
        search:"Búsqueda",
        location:"Ubicación",
        home:"Hogar ",
        chats:"Chats",
        bookings:"Reservas",
        barberShops:"BARBERÍAS",
        available:"Disponible",
        freelancerBarbers:"BARBEROS FREELANCE",
        featuredProducts:"PRODUCTOS DESTACADOS",
        sold:"vendido",
        overView:"Visión general",
        saleTax:"Impuesto de venta",
        earnings:"Ganancias",
        upcomingBookings:"Próximas reservas",
        noUpcomingBookings:"No hay próximas reservas",
        newRequests:"Nuevas solicitudes",
        yesterday:"Ayer",
        addToCart:"Añadir al carrito",
        removeItem:"Quitar elemento",
        proceedToCart:"Ir al carrito",
        price:"Precio",
        orderedOn:"Ordenado el",
        cash:"Efectivo",
        card:"Tarjeta",
        paymentMethod:"Método de pago",
        
    },
    chats: {
        searchChats:"Buscar chats",
        message:"Mensaje",
        writeAMessage:"Escribir un mensaje",
        today:"Hoy",
        yesterday:"Ayer",
        
    },
    bookings: {
        proceedToCheckout:"Proceder al proceso de pago",
        address:"Dirección",
        bookings:"Reservas",
        atShop:"En la tienda",
        barber:"Barbero",
        serviceCharges:"Cargos por servicio",
        processingFee:"Tarifa de procesamiento",
        grandTotal:"Total general",
        chats:"Chats",
        seeLocatio:"Ver ubicaciones",
        history:"Historia",
        noBookingYet:"Aún no hay reservas",
        addReview:"Añadir una reseña",
        completed:"Completado",
        pending:"Pendiente",
        cancelAppointment:"Cancelar cita",
        
    },
    carts: {
        cartIsEmpty:"El carrito está vacío",

    },
    shopProfile: {
        rating:"Calificaciones",
        bookings:"Reservas",
        bookAppointment:"Reservar cita",
        about:"Acerca de",
        barbers:"Barberos",
        reviews:"Comentarios",
        noReviews:"No hay comentarios",
        locations:"Ubicaciones",
        seeEarnings:"Ver Ganancias",
        recentWork:"Trabajos recientes",
        markitonmap:"Márcalo en el mapa",
        more:"más",
        noRecentWork:"Sin trabajo reciente",
        
    },
    bookAppointment: {
        selectABarber:"Seleccione un barbero de la tienda",
        selectServices:"Seleccionar servicios",
        schedule:"Horario",
        enterTime:"Introduzca la hora",
        tapTochoose:"Toca para elegir",
        tapTochooseTime:"Toca para elegir Hora",
        sendRequest:"Enviar solicitud",
        availabity:"Disponibilidad",
        atHome:"En casa",
        atShop:"En la tienda",
        enterLocation:"Introduzca la ubicación",
        serviceType:"Tipo de servicio",
        totalPayable:"Total a pagar",
        
    },
    favourite: {
        favourite:"Favoritos",
        products:"Productos",
        barbers:"Barberos",
        shops:"Tiendas",
        
    },
    changePassword: {
        changePassword:"Cambiar contraseña",
        enterOldPassword:"Introduzca contraseñas antiguas",
        createNewPassword:"Crear nueva contraseña",
        confirmPassword:"Confirmar nueva contraseña",
        
    },
    orders: {
        orderDetails:"Detalles del pedido",
        yourOrder:"Sus pedidos",
        noOrderYet:"¡Aún no hay pedido!",
        history:"Historia",
        progress:"No hay pedidos en curso",
        
    },
    product: {
        editProducts:"Editar producto",
        addStock:"Añadir stock",
        update:"Actualizar",
        enterStock:"Entrar en stock",
        price:"Precio",
        sold:"Vendido",
        stock:"Acción",
        rating:"Clasificación",
        buyNow:"Comprar Ahora",
        itemAdded:"Artículo añadido al carrito",
        addToCart:"Añadir al carrito",
        
    },
    popupmenu: {
        myAccount:"Mi cuenta",
        myAccountSub:"Realizar cambios en tu cuenta",
        myWallet:"Mis carteras",
        myWalletSub:"Revisa tu billetera",
        myOrder:"Mis pedidos",
        myOrderSub:"Revisa tus pedidos anteriores",
        favourite:"Favorito",
        favouriteSub:"Comprueba tu favorito",
        yourAccount:"Su cuenta",
        changePassword:"Cambiar contraseña",
        
    },
    profile: {
        enterYourPassword:"Introduzca su contraseña",
        confirm:"Confirmar",
        yourAccount:"Su cuenta",
        name:"Nombre",
        currentLocation:"Ubicaciones actuales",
        emailAddress:"Dirección de correo electrónico",
        save:"Guardar",
        deleteAccount:"Eliminar cuenta",
        
    },
    pendingProfile: {
        profileUnderObe:"Perfil bajo observación",
        profileUnderObeSub:"Su perfil está actualmente bajo observación. Por favor, espere la aprobación. Si tiene alguna pregunta, póngase en contacto con nosotros.",
        goBack:"Volver",
        
    },
    search: {
        categories:"Categorías",
        barbers:"Barberos",
        barberShops:"Peluquerías",
        products:"Productos",
        
    },
    accountReject: {
        accountReject:"Rechazo de cuenta",
        accountRejectSub:"Lamentamos que tu cuenta haya sido rechazada",
        goback:"Volver",
        
    },
    bookingRequest: {
        placeOrder:"Realizar pedido",
        card:"Tarjeta",
        wallet:"Carteras",
        currentAmount:"Importe actual",
        fee:"Honorario",
        insufficient:"Lo sentimos, tiene un saldo de cantidad insuficiente",
        remainingAmount:"Importe restante",
        Doyouwanttodothis:"¿Quieres hacer esto",
        yes:"Sí",
        no:"No",
        barberRating:"Calificación de barbero",
        shopRating:"Calificación de la tienda",
        addReview:"Agregar reseña",
        cancelAppoint:"Cancelar cita",
        cancelled:"Anulado",
        Completed:"¡Completado!",
        
    },
    barberInfo: {
        addBarber:"Añade Barber a tu tienda",

    },
    cartSummary: {
        shippingFee:"Gastos de envío",
        total:"Total",
        
    },
    orderDetail: {
        productRating:"Valoración del producto",
        reviewProduct:"Revisar producto",
        tax:"Impuesto",
        shipping:"Naviero",
        grandTotal:"Total general",
        status:"Estado",
        trxCode:"Código TRX",
        copyCode:"Copiar código",
        deliveryAddress:"Dirección de entrega",
        markDeliver:"Marcar como entregado",
        markRecieved:"Marcar como recibido",
        
    },
    recentWork:"Trabajos recientes",
    logout:"logut",
    
    imageCrop: {
        zoom:"Zoom",
        rotate:"Rotar",
        close:"Cerrar",
        submit:"Enviar",
        addPhoto:"Añadir foto",
        otherDetails:"Otros detalles",
        title:"Título",
        price:"Precio",
        quantity:"Cantidad",
        features:"Caracteristicas",
        saveChanges:"Guardar cambios",
        upload:"Subir",
        
    },
    customCart: {
        noItemsAdded:"No se han añadido elementos",
        grandTotal:"Total general",
        createOrder:"Crear pedido",
        
    },
    locationAutoComplete: {
        useCurrent:"Usar ubicación actual",
        suggestions:"Sugerencias",
        
    },
    serviceName:"Nombre del servicio",
    servicePrice:"Precio del servicio",
    timeTobeDoneinMin:"Tiempo a realizar en min",
    update:"Actualizar",
    editName:"Editar nombre",
    editAbout:"Editar Acerca de",
    noRecentWork:"Sin trabajo reciente",
    editRecentWork:"Editar trabajo reciente",
    addWork:"Agregar trabajo",
    services:"Servicios",
    noServicesAvail:"No hay servicios disponibles",
    addService:"Agregar servicio",
    editService:"Servicio de edición",
    add:"Agregar",
    workingHours:"Horas de trabajo",
    updateWorkingHours:"Actualizar días y horas laborables",
    editLocation:"Editar ubicación",
    products:"Productos",
    seeAll:"Ver todo",
    productList:"Lista de productos",
    noProductAvail:"No hay productos disponibles",
    updateCover:"Actualizar portada",
    available:"Disponible",
    ratings:"Calificaciones",
    bookings:"Reservas",
    recentWork:"Trabajos recientes",
    about:"Acerca de",
    WorkingDays:"Día laborable",
    more:"",
    non:"No",
    barbers:"Barberos",
    barberEarnings:"Ganancias de Barberos",
    totalEarnings:"Ganancias totales ($)",
    pendingEarnings:"Pago pendiente($)",
    earningGraph:"Gráfico de ganancias",
    noBarbersAvail:"No hay barberos disponibles",
    noTransactionYet:"¡Aún no hay transacciones!",
    addTransactions:"Agregar transacciones",
    transactions:"Transacciones",
    pay:"Pagar",
    addBarber:"Añadir Barbero",
    addNewBarber:"Añadir nuevo barbero",
    yourBarber:"Tus barberos",
    noBarberAdded:"No se agregó barbero",
    createCustomBooking:"Crear reserva personalizada",
    history:"Historia",
    noBookingsYet:"¡Aún no hay reservas!",
    trackingCode:"Código de seguimiento",
    orderDetails:"Detalles del pedido",
    yourOrder:"Sus pedidos",
    noOrderYet:"Aún no hay pedidos",
    noOrdersInProgress:"Pedidos en curso",
    updateShippingPrice:"Actualizar precio de envío",
    uploadProduct:"Cargar producto",
    createCustomOrder:"Crear pedido personalizado",
    addNewProduct:"Agregar nuevo producto",
    youProducts:"Sus productos",
    shippingPrice:"Precio de envío",
    noProductsYet:"Aún no hay productos",
    withDraw:"Retirar",
    paymentMethod:"Método de pago",
    or:"O",
    bankDetails:"Datos bancarios",
    requestWithDraw:"Solicitar retiro",
    balance:"Equilibrar",
    password:"Contraseña",
    email:"Correo electrónico",
    donthaveaccount:"¿Aún no tienes una cuenta?",
    signup:"Únete",
    
};

