name: macos
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.1.2
  path_provider: ^2.0.5
  file_selector: ^1.0.0
  file_picker: ^5.3.1 
  image: ^4.0.17
  easy_folder_picker: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"
  rename: ^2.1.1
  # flutter pub global run rename --bundleId com.onatcipli.networkUpp
  # flutter pub global run rename --appname "Network Upp"
  
flutter_icons:
  image_path: "assets/brain.jpg"
  macos:
    generate: true
    image_path: "assets/brain.jpg"
  # How to use : flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  assets:
    - assets/